//go:build ignore

// gen_mathjax bundles the TeX input and SVG output of MathJax into mathjax/mathjax.js.gz, which RenderMath runs with
// goja, and copies the glyph ranges of its font into mathjax/fonts, which RenderMath runs when math needs them. It
// downloads MathJax from npm and bundles it with esbuild through go run, so it needs no node.
package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha512"
	"encoding/base64"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"slices"
	"strings"
)

const (
	esbuild = "github.com/evanw/esbuild/cmd/esbuild@v0.28.2"
	banner  = "// Code generated by gen_mathjax.go from MathJax 4.1.3, Apache License 2.0, The MathJax Consortium. DO NOT EDIT."
)

// tarball is an npm package with its checksum, and the files of it the bundle needs.
type tarball struct {
	name, url, integrity string
	keep                 func(name string) bool
}

var tarballs = []tarball{{
	name:      "@mathjax/src",
	url:       "https://registry.npmjs.org/@mathjax/src/-/src-4.1.3.tgz",
	integrity: "sha512-rIrWquuBSoJuoMBdC/1qD+AUHTorlccPicoVy6P2xbUgnuDBpCcpbHtOAsB8L3hdCHtNBg92lF8e3Fz+pkcQbw==",
	keep:      func(name string) bool { return name == "package.json" || strings.HasPrefix(name, "mjs/") },
}, {
	name:      "@mathjax/mathjax-newcm-font",
	url:       "https://registry.npmjs.org/@mathjax/mathjax-newcm-font/-/mathjax-newcm-font-4.1.3.tgz",
	integrity: "sha512-gzAB3dFHilHX1l5x2xUqRL+1jDQt3Fyza1DkEMVXWC4E8SvsGdlgEza47HYi2WhVcgfkvf4zgUGzuhbq3Pjlew==",
	keep: func(name string) bool {
		return name == "package.json" || strings.HasPrefix(name, "mjs/") || strings.HasPrefix(name, "svg/dynamic/")
	},
}}

// packages are the TeX packages of MathJax that cover what KaTeX reads on the web.
var packages = []string{
	"base", "ams", "amscd", "boldsymbol", "braket", "cancel", "color", "extpfeil", "gensymb", "mathtools",
	"newcommand", "textmacros",
}

// shapedRanges are glyph ranges of the font that MathJax draws a character at a time, which reverses right to left
// text and breaks letters that join. gen_mathjax leaves them out, so RenderMath shapes that text with system fonts,
// as a browser does.
var shapedRanges = []string{"arabic", "devanagari", "hebrew"}

// entry renders TeX to SVG for render(tex). Errors throw instead of drawing as red text, so RenderMath fails and the
// app shows the source. fontCache none draws glyphs in place instead of referencing them.
//
// loadFontFile, which loadMathJax defines, runs each glyph range. A range finds the font at the global where MathJax's
// components put it. A range left out keeps its empty setup, so MathJax writes its characters as text. measureText,
// which loadMathJax also defines, measures that text with the fonts that draw it, since MathJax measures text only
// in a browser.
const entry = `import {mathjax} from '@mathjax/src/mjs/mathjax.js';
import {TeX} from '@mathjax/src/mjs/input/tex.js';
import {SVG} from '@mathjax/src/mjs/output/svg.js';
import {liteAdaptor} from '@mathjax/src/mjs/adaptors/liteAdaptor.js';
import {RegisterHTMLHandler} from '@mathjax/src/mjs/handlers/html.js';
import {MathJaxNewcmFont} from '@mathjax/mathjax-newcm-font/mjs/svg.js';
%s
globalThis.MathJax = {_: {output: {fonts: {'mathjax-newcm': {svg_ts: {MathJaxNewcmFont}}}}}};
for (const file of Object.values(MathJaxNewcmFont.dynamicFiles)) {
  file.setup = () => {};
}
mathjax.asyncLoad = (file) => loadFontFile(file);
mathjax.asyncIsSynchronous = true;

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', {
  InputJax: new TeX({packages: %s, formatError: (jax, err) => { throw new Error(err.message); }}),
  OutputJax: new SVG({fontCache: 'none', fontData: MathJaxNewcmFont}),
});
doc.outputJax.measureTextNode = (text) => {
  const size = parseFloat(adaptor.getAttribute(text, 'font-size')) / 1000;
  const [w, h, d] = measureText(adaptor.textContent(text), adaptor.getAttribute(text, 'font-family') || 'serif',
    adaptor.getAttribute(text, 'font-style') === 'italic', adaptor.getAttribute(text, 'font-weight') === 'bold');
  return {w: w * size, h: h * size, d: d * size};
};
globalThis.render = (tex) => adaptor.innerHTML(doc.convert(tex, {display: true}));
`

func main() {
	modules, err := os.MkdirTemp("", "mathjax-modules")
	if err != nil {
		log.Fatalf("failed to create module folder: %v", err)
	}
	defer os.RemoveAll(modules)

	for _, t := range tarballs {
		if err := download(t, filepath.Join(modules, filepath.FromSlash(t.name))); err != nil {
			log.Fatal(err)
		}
	}

	var imports, names strings.Builder
	for _, p := range packages {
		dir := filepath.Join(modules, "@mathjax", "src", "mjs", "input", "tex", p)
		configs, _ := filepath.Glob(filepath.Join(dir, "*Configuration.js"))
		if len(configs) != 1 {
			log.Fatalf("failed to find the configuration of TeX package %s: %v", p, configs)
		}
		fmt.Fprintf(&imports, "import '@mathjax/src/mjs/input/tex/%s/%s';\n", p, filepath.Base(configs[0]))
		fmt.Fprintf(&names, "'%s', ", p)
	}

	dir, err := os.MkdirTemp("", "mathjax-entry")
	if err != nil {
		log.Fatalf("failed to create entry folder: %v", err)
	}
	defer os.RemoveAll(dir)

	entryPath := filepath.Join(dir, "entry.js")
	script := fmt.Sprintf(entry, imports.String(), "["+strings.TrimSuffix(names.String(), ", ")+"]")
	if err := os.WriteFile(entryPath, []byte(script), 0o600); err != nil {
		log.Fatalf("failed to write entry: %v", err)
	}

	bundle := filepath.Join(dir, "mathjax.js")
	cmd := exec.Command("go", "run", esbuild, entryPath, "--bundle", "--platform=neutral", "--format=iife",
		"--target=es2015", "--minify", "--legal-comments=none", "--banner:js="+banner, "--outfile="+bundle)
	cmd.Env = append(os.Environ(), "NODE_PATH="+modules)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("failed to bundle mathjax: %v", err)
	}

	if err := os.RemoveAll("mathjax"); err != nil {
		log.Fatalf("failed to clear mathjax: %v", err)
	}
	if err := os.MkdirAll(filepath.Join("mathjax", "fonts"), 0o755); err != nil {
		log.Fatalf("failed to create mathjax: %v", err)
	}

	if err := compress(bundle, filepath.Join("mathjax", "mathjax.js.gz")); err != nil {
		log.Fatal(err)
	}

	ranges, _ := filepath.Glob(filepath.Join(modules, "@mathjax", "mathjax-newcm-font", "svg", "dynamic", "*.js"))
	for _, r := range ranges {
		if slices.Contains(shapedRanges, strings.TrimSuffix(filepath.Base(r), ".js")) {
			continue
		}
		if err := compress(r, filepath.Join("mathjax", "fonts", filepath.Base(r)+".gz")); err != nil {
			log.Fatal(err)
		}
	}
}

// download extracts the files of tarball t that it keeps into dir, after checking the tarball against its checksum.
func download(t tarball, dir string) error {
	resp, err := http.Get(t.url)
	if err != nil {
		return fmt.Errorf("failed to download %s: %w", t.name, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("failed to download %s: %s", t.name, resp.Status)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to download %s: %w", t.name, err)
	}

	sum := sha512.Sum512(data)
	if got := "sha512-" + base64.StdEncoding.EncodeToString(sum[:]); got != t.integrity {
		return fmt.Errorf("%s tarball has checksum %s, want %s", t.name, got, t.integrity)
	}

	gz, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("failed to read %s tarball: %w", t.name, err)
	}

	tr := tar.NewReader(gz)
	for {
		h, err := tr.Next()
		if err == io.EOF {
			return nil
		} else if err != nil {
			return fmt.Errorf("failed to read %s tarball: %w", t.name, err)
		}

		// npm tarballs hold the package in a package folder
		name, ok := strings.CutPrefix(path.Clean(h.Name), "package/")
		if h.Typeflag != tar.TypeReg || !ok || strings.HasPrefix(name, "../") || !t.keep(name) {
			continue
		}

		file := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(file), 0o700); err != nil {
			return fmt.Errorf("failed to create %s: %w", filepath.Dir(file), err)
		}

		body, err := io.ReadAll(tr)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", name, err)
		}

		if err := os.WriteFile(file, body, 0o600); err != nil {
			return fmt.Errorf("failed to write %s: %w", file, err)
		}
	}
}

// compress writes file src gzipped to dst.
func compress(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return fmt.Errorf("failed to read %s: %w", src, err)
	}

	var buf bytes.Buffer
	zw, _ := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if _, err := zw.Write(data); err != nil {
		return fmt.Errorf("failed to compress %s: %w", src, err)
	}
	if err := zw.Close(); err != nil {
		return fmt.Errorf("failed to compress %s: %w", src, err)
	}

	if err := os.WriteFile(dst, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", dst, err)
	}

	return nil
}
