//go:build ignore

// gen_shortcodes writes the sorted emoji short names of goldmark-emoji to shortcodes.go. goldmark-emoji can look up a
// name but can't list them.
package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

var (
	shortNamesPattern = regexp.MustCompile(`ShortNames: \[\]string\{([^}]*)\}`)
	namePattern       = regexp.MustCompile(`"([^"]+)"`)
)

func main() {
	dir, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/yuin/goldmark-emoji").Output()
	if err != nil {
		log.Fatalf("failed to locate goldmark-emoji: %v", err)
	}

	src, err := os.ReadFile(filepath.Join(strings.TrimSpace(string(dir)), "definition", "github.go"))
	if err != nil {
		log.Fatalf("failed to read emoji definitions: %v", err)
	}

	var names []string
	for _, list := range shortNamesPattern.FindAllStringSubmatch(string(src), -1) {
		for _, name := range namePattern.FindAllStringSubmatch(list[1], -1) {
			names = append(names, name[1])
		}
	}

	slices.Sort(names)
	names = slices.Compact(names)

	var out strings.Builder
	out.WriteString("// Code generated by gen_shortcodes.go. DO NOT EDIT.\n\npackage ui\n\n")
	out.WriteString("// shortcodes are the sorted emoji short names that markdown turns into emoji.\nvar shortcodes = []string{\n")
	for _, name := range names {
		fmt.Fprintf(&out, "\t%q,\n", name)
	}
	out.WriteString("}\n")

	if err := os.WriteFile("shortcodes.go", []byte(out.String()), 0o644); err != nil {
		log.Fatalf("failed to write shortcodes.go: %v", err)
	}
}
